language: node_js
node_js: "10"
cache: yarn
env:
  global:
    - secure: Jwf6eHnVf1Wb1n6RUmnRoBeH6McHNMKN+tnXlMP3RGIpEXR4rz5QlLByBTT/X6FcVD8o7gUzsHeYuFQeOWvflpLjAe7i87c8cts3OFyA9XUhW3vLUaK/046E7l7wkLgojseD3IoqIchJVk3ByjKjp9q3vLhbgS72izEXs4eoFdAp0uP8fVT+Xya/a2+Eqz9QuSXGSyWa8nW+HkOEO16rqntGLinc72acC1yrfXoOmFgrrnKsOsvqh8XlaE1XhrRkMwG3xPjSTp/IJQPzua5zAIxhO2lw/OmYWoKZgYeT6o7uwcwJA0xLPrYLjs2X37Lyvtc+nc1gu/HHqEMLlayMr8DwiYrbT2WP3D1m0N3cjsPmkIWf9mhgtL9u99k1XziumN0BnUoplGSik/ZS/QTGx2S4K+7OiQG/9gU4zH3gvuGC0QeblRVS7ieOppi6+dKAbBzAiN5sZGRN5EtJ1tSyV1IcqJY2ygMSAT3C/FG7Uy5RIDpESEr44nUDw7AZS648rhXCOAC1OVdoluZdNk89mHsPptHVcfWMtmrvSKl5RUMEh9n5GvG2H9ftWu2tlvKyyf30FgSfX9ny/0DUajcW5vEFSJiwZrkqnWhbIguFS0JJgf3Js42Tmo83NRISW7z6wbPG+bjhvJX9vAEjnvPkk/K+AppSEx/dMAbkZ1VANVg=
    - secure: RQjCgMg2NHtjP7qZDNSXjcX0wKm9A9NVcnszamDNp79ljUK9s8JmBUEF/nmraoV38a5WrrfQvvBJGY3kTm/UFdItblcsmNm2fWixuRhc1QPtOhB765SKYVus4v87cN/CI4teUmDC118gQHVfg/elkqUjbFg5nmhcSK1V+wQi3DIdRDtmmob4VcBKimQHGHYQgXx0Am16BnVcVeLV28U77hp9f4Cle4vEn0n3Waaum2upaoF/WQGzFHap9yRKghARSZ8Rxd2CgGFbFQuXlll7evV21RHmOTmef4ENZ27KuWiBBnxosALnOqc+J/ah00HoNHcswgjuQdWWXhM8pUAr3oP9dciJcaf77jkpB6ICxsj/k0Ykl7crJuKQYO2MmYi4Hx9FX+wfaxIPxmApErxGDqFb8ornY277iW7REaBykml5BqPENS607KWYmpSFNduMC7HK15ntaeOCWV0isLc0TMkcENdepA5s7llViOhO2dfn0flrZtAZ5NdGbIcspF8rg+vnA42VJJ2VEh2VWyGveYkcUcJiYVRh1srycAc8uJYzj65fuUOLzzGkJh/q7gh2HrofBk5fD50tbKFHCf+3+nG8D7Tt6vWzpJ4I1gadyjtMeiIK3tmwUDfAl7sHkmC4pOlqZA1pMiPqgxLrER672QLYmD2AjvdS3hqGExCZVi0=
    - GIT_NAME="Eloy Durán"
    - GIT_EMAIL="eloy.de.enige@gmail.com"
    - GH_USER="alloy"

script:
  - yarn lint
  - yarn test
  - yarn build

before_deploy:
  - echo "NPM_TOKEN=${NPM_TOKEN}" >> .env
  - echo "GH_TOKEN=${GH_TOKEN}" >> .env
  - git config --local user.name "${GIT_NAME}"
  - git config --local user.email "${GIT_EMAIL}"
  - git remote rm origin
  - git remote add origin https://${GH_USER}:${GH_TOKEN}@github.com/relay-tools/relay-compiler-language-typescript.git
  - git pull origin master
  - git branch --set-upstream-to origin/master
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
